# Generated by Django 5.1.2 on 2024-11-13 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_exemplar', models.CharField(max_length=50, unique=True)),
                ('data_inclusao', models.DateField(auto_now_add=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplares',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('editora', models.CharField(blank=True, max_length=255, null=True)),
                ('assunto', models.CharField(blank=True, max_length=100, null=True)),
                ('edicao', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Admin'), ('bibliotecario', 'Bibliotecário'), ('professor', 'Professor'), ('aluno', 'Aluno'), ('externo', 'Externo')], max_length=50)),
                ('numero_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Em Aberto', max_length=50)),
                ('atraso', models.BooleanField(default=False)),
                ('renovacoes', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.exemplar')),
            ],
        ),
        migrations.AddField(
            model_name='exemplar',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.livro'),
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_geracao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pendente', max_length=50)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('status_reserva', models.CharField(default='Ativa', max_length=50)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.exemplar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
